name = "SequencerJulia"
uuid = "348581b9-6e84-42e0-ac4e-fe9177c221e6"
authors = ["a5vzener <c.difficile@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
